version: "3.7"

services:

  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    environment:
      - TZ=America/Colombia/Bogota
    volumes:
      - nfs_plex_data:/root/Library/Application Support/Plex Media Server
      - nfs_media:/media
      - nfs_tmp:/tmp
    restart: unless-stopped
    network_mode: "host"

  transmission:
    image: jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - nfs_downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - nfs_downloads:/downloads
      - nfs_media:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=1001
      - PGID=1001
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=p3l4d0_N3RD
    restart: unless-stopped

volumes:
  nfs_plex_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.11.0.5,nfsvers=4,nolock
      device: "/volume1/plex/plex_data"
  nfs_media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.11.0.5,nfsvers=4,nolock
      device: "/volume1/plex/media_data"
  nfs_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.11.0.5,nfsvers=4,nolock
      device: "/volume1/plex/downloads_data"
  nfs_tmp:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.11.0.5,nfsvers=4,nolock
      device: "/volume1/plex/tmp_data"